### ISSUE TITLE
Setup spotify's API

### ISSUE THREAD

**Issue by aakashDhalDev** [shubham151/Ongaku#3]
We have the keys in group chat. Use it to fetch data and check if all the emotion parameters are there or not. Use this blog for reference: [https://mohithsubbarao.medium.com/moodtape-using-spotify-api-to-create-mood-generated-playlists-6e1244c70892](https://mohithsubbarao.medium.com/moodtape-using-spotify-api-to-create-mood-generated-playlists-6e1244c70892)

**Comment by DhanushRadhakrishna** [comment]
I'm taking this
